apiVersion: 1

datasources:
  - name: Zabbix
    type: alexanderzobnin-zabbix-datasource
    access: proxy
    url: ${ZABBIX_API_URL}
    basicAuth: false
    jsonData:
      keepCookies: []
      tlsSkipVerify: false
      httpMethod: POST
    secureJsonData:
      apitoken: ${ZABBIX_API_TOKEN}
    isDefault: false
    editable: true
  - name: JSON API
    type: marcusolsson-json-datasource
    access: proxy
    url: ${JSON_API_URL}
    jsonData:
      httpHeaderName1: Authorization
      httpHeaderValue1: Bearer ${JSON_API_BEARER_TOKEN}
    basicAuth: false
    isDefault: false
    editable: true
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    basicAuth: false
    isDefault: false
    editable: true
